### ISSUE TITLE
Build Script

### ISSUE THREAD

**Issue by Mr-Thack** [amuhak/MATH1554#4]
I understand that you're using Obsidian to compile things, but you need a build script.  
I'll go write one soon with pdflatex.

**Comment by amuhak** [comment]
That would be great! But in my short time experimenting with it an external compiler seams to mess up the latex equations sometimes.

**Comment by Mr-Thack** [comment]
LolOn Nov 17, 2023, at 7:50 PM, Amulya Jain ***@***.***> wrote:﻿
Closed #4 as not planned.
